### ISSUE TITLE
Tooltip on lamps

### ISSUE THREAD

**Issue by horseyhorsey** [mjocean/OscSwitchMatrixGUI#1]
Just had a quick look to see where this tooltip is on the switches but couldn't find it.

Possible to get on lamps too?

**Comment by mjocean** [comment]
If you hover over switch buttons, you should see the tool tip that contains the name. If not, let me know, as well as what OS you're running and what version of wxPython. 




As for lamps, i wanted that functionality  too --sadly they are circles that are drawn on and not widgets, so it was harder to add tool tips since circles don't have them. Instead, if you switch into layout mode, clicking near a lamp will tell you the name of the closest lamp in the console.  Should help if you're wondering what lamp is what. 




On Thu, Dec 28, 2017 at 10:12 AM -0500, "Dave" <notifications@github.com> wrote:












Just had a quick look to see where this tooltip is on the switches but couldn't find it.


Possible to get on lamps too?

**Comment by horseyhorsey** [comment]
Sorry that was a bit confusing , even for me. :) I had looked through the code to see how tooltips were done for the switches and so I could add to the lamps.

"clicking near a lamp will tell you the name of the closest lamp in the console"
Ah I see, perfect, I never took notice of that! Cheers!

I had a couple of freak lamps on PF that were not in use and just felt it was too long to go through and find them.
